/**
 * The Teams app package of the HEIG Quiz bot (ADR-030), served at
 * `GET /app/api/notifications/teams/app.zip` for a user to upload into their
 * own Teams ("Upload a customised app"): `manifest.json` and its two icons.
 *
 * Built from the configuration on the fly and DETERMINISTIC — the same
 * configuration gives the same bytes (fixed entry order, fixed timestamps) —
 * so a user who uploads it twice uploads the same app. `TEAMS_APP_VERSION` is
 * bumped by hand whenever the manifest changes; Teams offers the update to
 * those who uploaded an older one.
 *
 * The icons are compiled in (`teamsIcons.ts`, generated by
 * `apps/web/scripts/icons.mjs`): nothing is read from disk at run time, so
 * no volume mounted over the image can hide them.
 */
import { zipSync } from "fflate";

import { TEAMS_COLOR_PNG, TEAMS_OUTLINE_PNG } from "./teamsIcons.js";

/** Bump by hand on any change of the manifest below (semver, as Teams wants it). */
export const TEAMS_APP_VERSION = "1.0.0";
const MANIFEST_VERSION = "1.17";
/** The red of the logo, as the icons use it. */
const ACCENT = "#D60008";

export function teamsManifest(opts: { appId: string; publicUrl: string }): Record<string, unknown> {
  const site = opts.publicUrl.replace(/\/+$/, "");
  return {
    $schema: `https://developer.microsoft.com/en-us/json-schemas/teams/v${MANIFEST_VERSION}/MicrosoftTeams.schema.json`,
    manifestVersion: MANIFEST_VERSION,
    version: TEAMS_APP_VERSION,
    id: opts.appId,
    developer: {
      name: "HEIG-VD",
      websiteUrl: site,
      privacyUrl: site,
      termsOfUseUrl: site,
    },
    name: { short: "HEIG Quiz", full: "HEIG Quiz notifications" },
    description: {
      short: "Your HEIG Quiz notifications, in Teams.",
      full:
        "HEIG Quiz sends you its notifications in this chat: released results, pools shared with you. " +
        "Link the chat to your Quiz account once, then choose in the platform's settings which notifications reach you here. " +
        "Les notifications de HEIG Quiz dans Teams : liez cette conversation à votre compte Quiz, puis choisissez dans vos réglages ce qui vous parvient ici.",
    },
    icons: { color: "color.png", outline: "outline.png" },
    accentColor: ACCENT,
    bots: [
      {
        botId: opts.appId,
        scopes: ["personal"],
        supportsFiles: false,
        isNotificationOnly: false,
      },
    ],
    validDomains: [new URL(site).host],
  };
}

/** One timestamp for every entry: no clock in a deterministic archive. */
const ZIP_MTIME = new Date("2026-01-01T00:00:00Z");

/** The whole package, ready to serve: stored entries, fixed order and dates. */
export function teamsAppPackage(opts: { appId: string; publicUrl: string }): Buffer {
  const stored = (data: Uint8Array) => [data, { level: 0, mtime: ZIP_MTIME }] as [Uint8Array, { level: 0; mtime: Date }];
  const manifest = `${JSON.stringify(teamsManifest(opts), null, 2)}\n`;
  return Buffer.from(
    zipSync({
      "manifest.json": stored(new TextEncoder().encode(manifest)),
      "color.png": stored(Buffer.from(TEAMS_COLOR_PNG, "base64")),
      "outline.png": stored(Buffer.from(TEAMS_OUTLINE_PNG, "base64")),
    }),
  );
}
