/**
 * The Teams app of HEIG Quiz (ADR-030), served at
 * `GET /app/api/notifications/teams/app.zip` for a user to upload into their
 * own Teams ("Upload a customised app"): `manifest.json`, its French
 * localization `fr.json` and the two icons. And what a delivery needs of the
 * same app: the activity type of a kind and the deep link to the tab.
 *
 * The app is a personal tab (`/teams`, where the user links their account)
 * plus the right to post to its user's activity feed: the resource-specific
 * permission `TeamsActivity.Send.User`, which Teams asks the user to grant
 * when they install it — no tenant administrator. `webApplicationInfo`
 * names the Entra application, for the tab's SSO and for Graph to match the
 * app to our client-credentials token.
 *
 * Built from the configuration on the fly and DETERMINISTIC — the same
 * configuration gives the same bytes (fixed entry order, fixed timestamps) —
 * so a user who uploads it twice uploads the same app. `TEAMS_APP_VERSION` is
 * bumped by hand whenever the package changes; Teams offers the update to
 * those who uploaded an older one.
 *
 * Every user-facing string comes from the server dictionary
 * (`templates.ts`): English in the manifest, French in `fr.json`.
 *
 * The icons are compiled in (`teamsIcons.ts`, generated by
 * `apps/web/scripts/icons.mjs`): nothing is read from disk at run time, so
 * no volume mounted over the image can hide them.
 */
import { zipSync } from "fflate";

import type { NotificationKind, NotificationPayload } from "@quiz/contracts";

import type { ActivityNotification } from "./teams.js";
import { TEAMS_COLOR_PNG, TEAMS_OUTLINE_PNG } from "./teamsIcons.js";
import {
  activityParameters,
  notificationPath,
  serverText,
  type MailLocale,
  type RenderedNotification,
} from "./templates.js";

/** Bump by hand on any change of the package below (semver, as Teams wants it). */
export const TEAMS_APP_VERSION = "2.1.0";
const MANIFEST_VERSION = "1.17";
const SCHEMAS = `https://developer.microsoft.com/en-us/json-schemas/teams/v${MANIFEST_VERSION}`;
/** The red of the logo, as the icons use it. */
const ACCENT = "#D60008";
/** The one static tab's `entityId`: what a deep link opens. */
export const TEAMS_TAB_ENTITY = "home";

/**
 * The kinds the manifest declares an activity type for, in its order. It
 * RUNS AHEAD of `NOTIFICATION_KINDS` (ADR-030 §f): every user re-uploads the
 * app for a new version, so the one bump of #198 step 4 already declares the
 * kinds its later steps emit. A kind of the catalogue missing here is a
 * compile error below (and a test).
 */
export const TEAMS_ACTIVITY_KINDS = [
  "results_released",
  "pool_shared",
  "pool_ownership",
  "student_joined",
  "roster_conflict",
  "grading_ready",
  "pool_question_added",
  "activity_scheduled",
  "activity_available",
  "deadline_approaching",
  "results_updated",
] as const;
type TeamsActivityKind = (typeof TEAMS_ACTIVITY_KINDS)[number];

/** Every kind of the catalogue has its activity type: `true` or a compile error. */
const CATALOGUE_DECLARED: [NotificationKind] extends [TeamsActivityKind] ? true : false = true;
void CATALOGUE_DECLARED;

/** The activity type of each kind, as the manifest declares it and a delivery names it. */
export const TEAMS_ACTIVITY_TYPES: Record<TeamsActivityKind, string> = {
  results_released: "resultsReleased",
  pool_shared: "poolShared",
  pool_ownership: "poolOwnership",
  student_joined: "studentJoined",
  roster_conflict: "rosterConflict",
  grading_ready: "gradingReady",
  pool_question_added: "poolQuestionAdded",
  activity_scheduled: "activityScheduled",
  activity_available: "activityAvailable",
  deadline_approaching: "deadlineApproaching",
  results_updated: "resultsUpdated",
};

interface AppOptions {
  appId: string;
  /** `PUBLIC_URL`, without a trailing slash (`config.ts` normalizes it). */
  publicUrl: string;
}

/**
 * The localizable strings of the package, keyed as Teams' localization
 * schema names them (`name.short`, `staticTabs[0].name`,
 * `activities.activityTypes[0].templateText`, …), in one language. The
 * manifest takes the English values in place, `fr.json` the French ones.
 */
export function teamsAppStrings(locale: MailLocale): Record<string, string> {
  const t = serverText(locale);
  const strings: Record<string, string> = {
    "name.short": t["app.name.short"],
    "name.full": t["app.name.full"],
    "description.short": t["app.description.short"],
    "description.full": t["app.description.full"],
    "staticTabs[0].name": t["app.tab.name"],
  };
  TEAMS_ACTIVITY_KINDS.forEach((kind, i) => {
    strings[`activities.activityTypes[${i}].description`] = t[`activity.${kind}.description`];
    strings[`activities.activityTypes[${i}].templateText`] = t[`activity.${kind}.template`];
  });
  return strings;
}

function teamsManifest(opts: AppOptions): Record<string, unknown> {
  const site = opts.publicUrl;
  const host = new URL(site).host;
  const en = teamsAppStrings("en");
  return {
    $schema: `${SCHEMAS}/MicrosoftTeams.schema.json`,
    manifestVersion: MANIFEST_VERSION,
    version: TEAMS_APP_VERSION,
    id: opts.appId,
    localizationInfo: {
      defaultLanguageTag: "en",
      additionalLanguages: [{ languageTag: "fr", file: "fr.json" }],
    },
    developer: {
      name: "HEIG-VD",
      websiteUrl: site,
      privacyUrl: site,
      termsOfUseUrl: site,
    },
    name: { short: en["name.short"], full: en["name.full"] },
    description: { short: en["description.short"], full: en["description.full"] },
    icons: { color: "color.png", outline: "outline.png" },
    accentColor: ACCENT,
    staticTabs: [
      {
        entityId: TEAMS_TAB_ENTITY,
        name: en["staticTabs[0].name"],
        contentUrl: `${site}/teams`,
        websiteUrl: site,
        scopes: ["personal"],
      },
    ],
    validDomains: [host],
    webApplicationInfo: { id: opts.appId, resource: `api://${host}/${opts.appId}` },
    authorization: {
      permissions: { resourceSpecific: [{ type: "Application", name: "TeamsActivity.Send.User" }] },
    },
    activities: {
      activityTypes: TEAMS_ACTIVITY_KINDS.map((kind, i) => ({
        type: TEAMS_ACTIVITY_TYPES[kind],
        description: en[`activities.activityTypes[${i}].description`],
        templateText: en[`activities.activityTypes[${i}].templateText`],
      })),
    },
  };
}

/** `fr.json`: the French strings, under the localization schema. */
export function teamsLocalization(locale: MailLocale): Record<string, unknown> {
  return {
    $schema: `${SCHEMAS}/MicrosoftTeams.Localization.schema.json`,
    ...teamsAppStrings(locale),
  };
}

/** One timestamp for every entry: no clock in a deterministic archive. */
const ZIP_MTIME = new Date("2026-01-01T00:00:00Z");

/** The whole package, ready to serve: stored entries, fixed order and dates. */
export function teamsAppPackage(opts: AppOptions): Buffer {
  const stored = (data: Uint8Array) => [data, { level: 0, mtime: ZIP_MTIME }] as [Uint8Array, { level: 0; mtime: Date }];
  const json = (value: unknown) => new TextEncoder().encode(`${JSON.stringify(value, null, 2)}\n`);
  return Buffer.from(
    zipSync({
      "manifest.json": stored(json(teamsManifest(opts))),
      "fr.json": stored(json(teamsLocalization("fr"))),
      "color.png": stored(Buffer.from(TEAMS_COLOR_PNG, "base64")),
      "outline.png": stored(Buffer.from(TEAMS_OUTLINE_PNG, "base64")),
    }),
  );
}

/**
 * The Teams deep link to the app's tab, carrying where the notification
 * leads as the tab's `subEntityId`: the app path the bell and the e-mail
 * open (`notificationPath`). The tab never follows it as given — it parses
 * it into a route of the router and writes the path back from that route,
 * under its own origin (`TeamsTabPage`).
 */
export function teamsTabDeepLink(appId: string, payload: NotificationPayload): string {
  const context = JSON.stringify({ subEntityId: notificationPath(payload) });
  return `https://teams.microsoft.com/l/entity/${encodeURIComponent(appId)}/${TEAMS_TAB_ENTITY}?context=${encodeURIComponent(context)}`;
}

/**
 * The activity-feed notification of one payload, for one recipient:
 * `message` is the notification rendered in their platform language
 * (`renderNotification`), of which the activity takes the topic and the
 * preview line.
 */
export function teamsActivity(
  appId: string,
  payload: NotificationPayload,
  message: Pick<RenderedNotification, "topic" | "preview">,
): ActivityNotification {
  return {
    topic: message.topic,
    webUrl: teamsTabDeepLink(appId, payload),
    activityType: TEAMS_ACTIVITY_TYPES[payload.kind],
    previewText: message.preview,
    templateParameters: activityParameters(payload),
  };
}
